// // Dates
//  let myDate = new Date()
// //  console.log(myDate.toJSON());
// //  console.log(typeof myDate);
 
// // let myCreatedDate = new Date(25 , 2 , 25)
// // // console.log(myCreatedDate.toDateString());
// // let myCreatedDate = new Date("02-22-2025")
// // console.log(myCreatedDate.toLocaleDateString());

// let newdate = new Date()
// console.log(newdate.getMonth());
// console.log(newdate.getDay());

let mydate = new Date()
// console.log(mydate.toString());

// let myCreatedDate = new Date(25 , 2 , 2025);
// console.log(myCreatedDate.toDateString());

let myCreatedDate = new Date("02-22-2025")
console.log(myCreatedDate.toLocaleTimeString());
